# Generated by Django 4.1.5 on 2023-01-07 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_listings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listings',
            name='photo',
        ),
        migrations.AddField(
            model_name='listings',
            name='description',
            field=models.TextField(default='SOME STRING', max_length=256),
        ),
    ]
