# Generated by Django 4.1.5 on 2023-01-07 20:21

import auctions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_remove_listings_photo_listings_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='photo',
            field=models.ImageField(default='Photo', upload_to=auctions.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='listings',
            name='description',
            field=models.TextField(default='Description', max_length=256),
        ),
    ]
