# Generated by Django 4.1.5 on 2023-01-08 11:19

import auctions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_listings_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='image',
            field=models.ImageField(blank=True, default='Photo', upload_to=auctions.models.user_directory_path),
        ),
    ]
